/* =========================================
   DECODE THE WORD - ENHANCED BONUS CONTENT
   Jokes, Facts, and Quotes (Grade-Banded)
   ========================================= */

window.BONUS_BANK = {
  facts: [
    "Honey never spoils and can last thousands of years.",
    "Octopuses have three hearts and blue blood.",
    "A group of flamingos is called a flamboyance.",
    "Your brain uses about 20% of your body's energy.",
    "Bananas are berries, but strawberries are not.",
    "Wombat poop is cube-shaped due to intestine structure.",
    "A day on Venus is longer than a year on Venus.",
    "Butterflies taste with their feet using special sensors.",
    "Sharks have existed longer than trees on Earth.",
    "Sea otters hold hands while sleeping to stay together.",
    "A cloud can weigh over a million pounds.",
    "Koalas have fingerprints nearly identical to humans.",
    "Some frogs can freeze solid and thaw alive.",
    "The heart of a shrimp is located in its head.",
    "A group of crows is called a murder.",
    "The Eiffel Tower grows taller in summer heat.",
    "There are more stars than grains of sand on many beaches.",
    "Plants can communicate through underground fungal networks.",
    "Owls can turn their heads 270 degrees because of special neck bones.",
    "Water can boil and freeze simultaneously at the triple point.",
    "Jellyfish have existed for over 500 million years.",
    "The fastest land animal is the cheetah reaching 70 mph.",
    "Some volcanoes exist underwater in the ocean depths.",
    "The Amazon rainforest produces 20% of Earth's oxygen.",
    "A single tree can be home to thousands of species.",
    "Some birds migrate over 10,000 miles without stopping.",
    "The human body has 206 bones when fully grown.",
    "Your tongue print is as unique as your fingerprint.",
    "Antarctica is technically a desert despite all the ice.",
    "Some dinosaurs had feathers millions of years ago.",
    "Saturn would float if you had an ocean big enough.",
    "A compass points to magnetic north, not true north.",
    "The ocean has underwater mountains and waterfalls.",
    "Bioluminescent fish create their own light chemically.",
    "The Milky Way galaxy contains over 200 billion stars.",
    "Rocks cycle through forms over millions of years.",
    "Your bones are living tissue that constantly rebuild.",
    "Some spiders can fly using silk like a balloon.",
    "Seeds can remain dormant for decades before sprouting.",
    "Whale songs can travel thousands of miles underwater.",
    "Lightning is five times hotter than the sun's surface.",
    "Giraffes have the same number of neck bones as humans: seven.",
    "A sneeze travels at about 100 miles per hour.",
    "Bamboo can grow three feet in just 24 hours.",
    "Dolphins have names for each other using unique whistles.",
    "The human eye can distinguish about 10 million colors.",
    "Bees can recognize human faces using pattern recognition.",
    "Sound travels faster through water than through air.",
    "The shortest war in history lasted only 38 minutes.",
    "A bolt of lightning contains one billion volts.",
    "Polar bear fur is actually transparent, not white.",
    "The human nose can detect over one trillion scents.",
    "Spiders are found on every continent except Antarctica.",
    "A single raindrop falls at about 20 mph.",
    "The Pacific Ocean is larger than all land combined.",
    "Chameleons change color based on mood and temperature.",
    "The Moon is slowly drifting away from Earth each year.",
    "A hummingbird's heart beats 1,200 times per minute.",
    "Trees can send distress signals through root systems.",
    "The smallest bone in your body is in your ear.",
    "Goldfish can learn to recognize their owners.",
    "A year on Mercury is just 88 Earth days long.",
    "Elephants can hear sounds humans cannot detect.",
    "The coldest place in the universe is right here on Earth.",
    "Penguins propose to mates with a special pebble.",
    "Your stomach gets a new lining every few days.",
    "A group of porcupines is called a prickle.",
    "The longest living animal is a type of clam.",
    "Diamonds form deep underground under extreme pressure.",
    "A blue whale's heart is the size of a small car.",
    "Ants can lift objects 50 times their body weight.",
    "The tongue is the strongest muscle relative to size.",
    "A sneeze temporarily stops your heart for a millisecond.",
    "Camels can drink 30 gallons of water in 13 minutes.",
    "The longest hiccupping spree lasted 68 years.",
    "A crocodile cannot stick out its tongue.",
    "The average person walks 75,000 miles in a lifetime.",
    "Fingernails grow four times faster than toenails.",
    "Hot water freezes faster than cold water sometimes.",
    "A mantis shrimp can punch with the force of a bullet.",
    "The human body contains enough carbon to make 900 pencils.",
    "Cats spend 70% of their lives sleeping.",
    "The shortest complete sentence in English is \"I am.\"",
    "A dragonfly can fly backwards and hover in place.",
    "The Great Wall of China is not visible from space.",
    "Your blood makes up about 8% of your body weight.",
    "A flea can jump 200 times its body length.",
    "The world's oldest known recipe is for beer.",
    "Cows have best friends and get stressed when separated.",
    "The human brain is about 75% water.",
    "A day on Jupiter is less than 10 hours long.",
    "Apples float because they're 25% air by volume.",
    "The inventor of the Frisbee was turned into a Frisbee.",
    "Sloths can hold their breath longer than dolphins.",
    "A single strand of spider silk is stronger than steel.",
    "The world's quietest room absorbs 99.99% of sound.",
    "Peanuts are not actually nuts; they're legumes.",
    "A rainbow is actually a full circle from the right angle.",
    "The longest English word without a vowel is \"rhythms.\"",
    "Humans share 60% of their DNA with bananas.",
    "A group of owls is called a parliament.",
    "The dot over the letter 'i' is called a tittle."
  ],

  jokes: [
    { q: "Why did the pencil cross the road?", a: "To draw the other side!" },
    { q: "What do you call a bear with no teeth?", a: "A gummy bear!" },
    { q: "Why did the scarecrow win an award?", a: "He was outstanding in his field!" },
    { q: "What do you call a sleeping dinosaur?", a: "A dino-snore!" },
    { q: "Why did the cookie go to the hospital?", a: "It felt crummy!" },
    { q: "What has hands but can't clap?", a: "A clock!" },
    { q: "Why did the math book look worried?", a: "It had too many problems!" },
    { q: "What do you call a fake noodle?", a: "An impasta!" },
    { q: "Why did the bike fall over?", a: "It was two-tired!" },
    { q: "What do you call cheese that isn't yours?", a: "Nacho cheese!" },
    { q: "Why don't eggs tell jokes?", a: "They might crack up!" },
    { q: "What do you call a fish wearing a bowtie?", a: "So-fish-ticated!" },
    { q: "Why was the broom late?", a: "It swept in!" },
    { q: "What kind of tree fits in your hand?", a: "A palm tree!" },
    { q: "Why did the tomato blush?", a: "It saw the salad dressing!" },
    { q: "What do you call an alligator detective?", a: "An investi-gator!" },
    { q: "Why did the music note go to school?", a: "To improve its pitch!" },
    { q: "What do you call a lazy kangaroo?", a: "A pouch potato!" },
    { q: "Why did the computer get cold?", a: "It left its Windows open!" },
    { q: "What do you call a snowman in summer?", a: "A puddle!" },
    { q: "Why did the astronaut break up with the moon?", a: "It needed space!" },
    { q: "What's a tornado's favorite game?", a: "Twister!" },
    { q: "Why did the student eat their homework?", a: "The teacher said it was a piece of cake!" },
    { q: "What do you call a boomerang that doesn't come back?", a: "A stick!" },
    { q: "Why don't scientists trust atoms?", a: "Because they make up everything!" },
    { q: "What did the ocean say to the beach?", a: "Nothing, it just waved!" },
    { q: "Why did the golfer bring two pairs of pants?", a: "In case they got a hole in one!" },
    { q: "What do you call a parade of rabbits hopping backward?", a: "A receding hare-line!" },
    { q: "Why did the picture go to jail?", a: "It was framed!" },
    { q: "What do you call a dog magician?", a: "A labracadabrador!" },
    { q: "Why did the banana go to the doctor?", a: "It wasn't peeling well!" },
    { q: "What do you call a belt made of watches?", a: "A waist of time!" },
    { q: "Why did the gym close down?", a: "It just didn't work out!" },
    { q: "What do you call a sleeping bull?", a: "A bulldozer!" },
    { q: "Why did the coffee file a police report?", a: "It got mugged!" },
    { q: "What do clouds wear under their clothes?", a: "Thunderwear!" },
    { q: "Why did the skeleton go to the party alone?", a: "They had no body to go with!" },
    { q: "What do you call a factory that makes okay products?", a: "A satisfactory!" },
    { q: "Why did the orange stop rolling down the hill?", a: "It ran out of juice!" },
    { q: "What do you call a dinosaur that crashes cars?", a: "Tyrannosaurus Wrecks!" },
    { q: "Why don't oysters donate to charity?", a: "Because they're shellfish!" },
    { q: "What do you call a group of disorganized cats?", a: "A cat-astrophe!" },
    { q: "Why did the scarecrow become a successful neurosurgeon?", a: "He was outstanding in his field!" },
    { q: "What do you call a can opener that doesn't work?", a: "A can't opener!" },
    { q: "Why did the bicycle keep falling over?", a: "It was two tired to stand!" },
    { q: "What do you call a bee that can't make up its mind?", a: "A maybe!" },
    { q: "Why did the cookie cry?", a: "Its mother was a wafer so long!" },
    { q: "What do you call a dinosaur with an extensive vocabulary?", a: "A thesaurus!" },
    { q: "Why did the calendar break up with the clock?", a: "It wanted more dates!" },
    { q: "What do you call a magical dog?", a: "A labracadabrador!" },
    { q: "Why was the equal sign so humble?", a: "It knew it wasn't greater or less than anyone!" },
    { q: "What do you call a shoe made from a banana?", a: "A slipper!" },
    { q: "Why did the teacher wear sunglasses?", a: "Because the students were so bright!" },
    { q: "What do you call an elephant that doesn't matter?", a: "An irrelephant!" },
    { q: "Why did the invisible man turn down the job?", a: "He couldn't see himself doing it!" },
    { q: "What do you call a cow with no legs?", a: "Ground beef!" },
    { q: "Why did the photon check into a hotel?", a: "It was traveling light!" },
    { q: "What do you call a snowman with a six-pack?", a: "An abdominal snowman!" },
    { q: "Why did the gym teacher go to the bank?", a: "To get their quarterback!" },
    { q: "What do you call a pile of cats?", a: "A meowtain!" },
    { q: "Why did the smartphone go to therapy?", a: "It lost its contacts!" },
    { q: "What do you call a bear in the rain?", a: "A drizzly bear!" },
    { q: "Why did the skeleton start a band?", a: "They had the organs but no body!" },
    { q: "What do you call a laughing motorcycle?", a: "A Yamahahaha!" },
    { q: "Why did the tree go to the dentist?", a: "To get a root canal!" },
    { q: "What do you call a sunburn on your brain?", a: "A no-brainer!" },
    { q: "Why did the duck go to rehab?", a: "It was a quack addict!" },
    { q: "What do you call a sleeping pizza?", a: "A piZZZZa!" },
    { q: "Why did the vacuum cleaner break up?", a: "The relationship sucked!" },
    { q: "What do you call a parade of rabbits?", a: "A hare-raising event!" },
    { q: "Why did the cell phone wear glasses?", a: "It lost all its contacts!" },
    { q: "What do you call a fancy potato?", a: "A spec-tater!" },
    { q: "Why did the envelope go to therapy?", a: "It had too many issues!" },
    { q: "What do you call a belt with a watch on it?", a: "A complete waste of time!" }
  ]
};

window.QUOTE_BANK = {
  k2: [
    { text: "Keep going. You can do hard things.", speaker: "Growth Mindset" },
    { text: "Mistakes help your brain grow stronger.", speaker: "Learning Science" },
    { text: "Try again with a brave heart.", speaker: "Courage" },
    { text: "Small steps add up to big journeys.", speaker: "Persistence" },
    { text: "Read, think, and wonder every day.", speaker: "Curiosity" },
    { text: "Be kind to yourself while you learn.", speaker: "Self-Compassion" },
    { text: "Questions are how we discover answers.", speaker: "Inquiry" },
    { text: "Your effort matters more than being perfect.", speaker: "Growth Mindset" },
    { text: "Everyone learns at their own speed.", speaker: "Individuality" },
    { text: "Practice makes progress, not perfect.", speaker: "Learning" }
  ],
  
  g3_5: [
    { text: "Be curious. Ask great questions.", speaker: "Inquiry" },
    { text: "Your effort matters more than the outcome.", speaker: "Growth Mindset" },
    { text: "Learning is an adventure, not a race.", speaker: "Journey" },
    { text: "A reader today is a leader tomorrow.", speaker: "Literacy" },
    { text: "Every expert was once a beginner.", speaker: "Progress" },
    { text: "Think before you speak and listen after.", speaker: "Communication" },
    { text: "Mistakes are proof you're trying new things.", speaker: "Risk-Taking" },
    { text: "Knowledge grows when shared with others.", speaker: "Collaboration" },
    { text: "Focus on progress, not perfection.", speaker: "Growth" },
    { text: "The best time to start is now.", speaker: "Action" },
    { text: "Character is what you do when no one's watching.", speaker: "Integrity" },
    { text: "Kindness costs nothing but means everything.", speaker: "Compassion" },
    { text: "You're capable of more than you know.", speaker: "Potential" },
    { text: "Learn from yesterday, live for today, hope for tomorrow.", speaker: "Wisdom" },
    { text: "It's not about knowing everything; it's about learning anything.", speaker: "Learning" }
  ],
  
  g6_8: [
    { text: "The expert in anything was once a beginner.", speaker: "Mastery" },
    { text: "Discipline is choosing what you want most over what you want now.", speaker: "Self-Control" },
    { text: "Confidence grows from keeping promises to yourself.", speaker: "Self-Trust" },
    { text: "Questions are the engines of learning.", speaker: "Inquiry" },
    { text: "Focus on improvement, not comparison.", speaker: "Personal Growth" },
    { text: "Logic without compassion is cold; compassion without logic is chaos.", speaker: "Balance" },
    { text: "Your habits shape your future more than your intentions.", speaker: "Character" },
    { text: "Thinking clearly is more valuable than thinking quickly.", speaker: "Critical Thinking" },
    { text: "The opposite of knowledge isn't ignorance; it's certainty.", speaker: "Humility" },
    { text: "Integrity is doing the right thing even when it's hard.", speaker: "Ethics" },
    { text: "You can't control what happens, only how you respond.", speaker: "Resilience" },
    { text: "Wisdom is knowing what to do next; virtue is doing it.", speaker: "Action" },
    { text: "Be suspicious of simple answers to complex problems.", speaker: "Critical Thinking" },
    { text: "The best argument wins, not the loudest voice.", speaker: "Reasoning" },
    { text: "Learn to spot when emotion is masquerading as logic.", speaker: "Awareness" }
  ],
  
  g9_12: [
    { text: "Education is the passport to the future.", speaker: "Malcolm X" },
    { text: "The more you learn, the more you can serve others.", speaker: "Service" },
    { text: "Clarity comes from action and reflection, not just thinking.", speaker: "Wisdom" },
    { text: "Your habits, not your intentions, determine your trajectory.", speaker: "Character" },
    { text: "Build skills that let you help others meaningfully.", speaker: "Purpose" },
    { text: "Question your assumptions before questioning others' facts.", speaker: "Intellectual Honesty" },
    { text: "The strongest arguments anticipate their own weaknesses.", speaker: "Critical Thinking" },
    { text: "Understanding context is as important as knowing content.", speaker: "Wisdom" },
    { text: "Logic reveals what is; ethics determines what ought to be.", speaker: "Philosophy" },
    { text: "True confidence is knowing you can learn what you don't know.", speaker: "Growth Mindset" },
    { text: "Data without interpretation is noise; interpretation without data is opinion.", speaker: "Analysis" },
    { text: "The map is not the territory; models are not reality.", speaker: "Epistemology" },
    { text: "Seek first to understand, then to be understood.", speaker: "Stephen Covey" },
    { text: "The future belongs to those who learn more skills than they'll need.", speaker: "Adaptability" },
    { text: "Intellectual humility is the foundation of genuine learning.", speaker: "Wisdom" }
  ]
};

console.log("✓ Enhanced bonus content loaded");
